# Local.
from pagetpalace.config import PAGETPALACEDEMO, PAGETPALACELIVE

LIVE_ACCESS_TOKEN = PAGETPALACELIVE['OANDA_ACCESS_TOKEN']
DEMO_ACCESS_TOKEN = PAGETPALACEDEMO['ACCESS_TOKEN']

# Live.
GBP_USD_ACCOUNT_NUMBER = PAGETPALACELIVE['GBP_USD_ACC_NUM']
HAMMER_PIN_POOL_ACCOUNT_NUMBER = PAGETPALACELIVE['HAMMER_PIN_POOL_ACC_NUM']
HEIKIN_ASHI_DAILY_LONG_POOL_ACCOUNT_NUMBER = PAGETPALACELIVE['HEIKIN_ASHI_DAILY_LONG_POOL_ACC_NUM']
HPDAILY_ACCOUNT_NUMBER = PAGETPALACELIVE['HPDAILY_ACC_NUM']
NAS100_ACCOUNT_NUMBER = PAGETPALACELIVE['NAS100_ACC_NUM']
PRIMARY_ACCOUNT_NUMBER = PAGETPALACELIVE['PRIMARY_ACC_NUM']
SPX500_ACCOUNT_NUMBER = PAGETPALACELIVE['SPX500_ACC_NUM']

# Demo.
DEMO_ACCOUNT_NUMBER = PAGETPALACEDEMO['V20_ACCOUNT_NUMBER']

PROTOCOL = 'https://'
OANDA_API_VERSION = 'v3'
OANDA_DOMAINS = {
    'LIVE_STREAM': 'stream-fxtrade.oanda.com',
    'DEMO_STREAM': 'stream-fxpractice.oanda.com',
    'LIVE_API': 'api-fxtrade.oanda.com',
    'DEMO_API': 'api-fxpractice.oanda.com',
}
