# Local.
from pagetpalace.config import PAGETPALACEDEMO, PAGETPALACELIVE

LIVE_ACCESS_TOKEN = PAGETPALACELIVE['OANDA_ACCESS_TOKEN']
DEMO_ACCESS_TOKEN = PAGETPALACEDEMO['ACCESS_TOKEN']

# Live.
IN50_ACCOUNT_NUMBER = PAGETPALACELIVE['IN50_ACC_NUM']
NAS100_ACCOUNT_NUMBER = PAGETPALACELIVE['NAS100_ACC_NUM']
PRIMARY_ACCOUNT_NUMBER = PAGETPALACELIVE['PRIMARY_ACC_NUM']
SPX500_ACCOUNT_NUMBER = PAGETPALACELIVE['SPX500_ACC_NUM']

# Demo.
DEMO_ACCOUNT_NUMBER = PAGETPALACEDEMO['V20_ACCOUNT_NUMBER']

PROTOCOL = 'https://'
OANDA_API_VERSION = 'v3'
OANDA_DOMAINS = {
    'LIVE_STREAM': 'stream-fxtrade.oanda.com',
    'DEMO_STREAM': 'stream-fxpractice.oanda.com',
    'LIVE_API': 'api-fxtrade.oanda.com',
    'DEMO_API': 'api-fxpractice.oanda.com',
}
